### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by ajaxvp** [superischroma/GreenHam#1]
Here is a list of the features that I want to finish for this project.
- [ ] Finish graphics for remaining 3 fields
- [ ] Finish level layouts for all 8 fields
- [ ] Create sound engine
- [ ] Compose tracks for each field and sound effects for events
- [ ] Add options menu with configurable values
- [ ] Add a final, smaller layout for a final level
- [ ] Add structures with traps inside of them
