### ISSUE TITLE
Entity To-Do List

### ISSUE THREAD

**Issue by ajaxvp** [superischroma/GreenHam#5]
List of game entities which have been completed or not.
- [x] Chop: The player
- [x] Bead: Collectable object used to win the game
- [ ] Super Cheese: Powerup which gives you invincibility
- [x] Banana: Slow moving entity which kills you when it touches you
- [x] Anti-Chop: Banana but faster
- [x] Black Hole: Natural hazard which drags you in and kills you if you reach its event horizon (SSF)
- [x] Speedster: Small ship which will shoot itself at you, getting hit by it will result in death (SSF)
- [x] Ice Shards: Falling objects which will kill the player if hit by them (SSF)
- [x] Meteor: Reskinned ice shards (FHF, SSF)
- [x] Sandzilla: Reskinned banana (SPF)
- [x] Quicksand: Reskinned black hole (SPF)
- [x] Spikes: Reskinned ice shards (SPF)
- [x] Gravitor: Floating object which attempts to send you flying into the ground (FHF)
- [ ] Thundercloud: Cloud which drops lightning on you from above (FHF)
- [ ] Lightning: Dropped from thunderclouds (FHF)
- [ ] Ewitch: Negative spell-shooting witch (MSF)
- [ ] Party Popper: Explosive which kills you if hit (MSF)
- [ ] Negative Spell: Drifting particles or shot by a witch that kills you on touch (MSF)
- [ ] Fish: Jumping fish (ADF)
- [ ] Chomper: Small creature which attempts to bite you (ADF)
- [x] Bubble Generator: Spawner for bubbles (ADF)
- [ ] Whirlpool: Reskinned black hole (ADF)
- [x] Needle: Collectable saving grace before dying
- [x] Sewing Kit: Collectable extra life
- [x] Bubble: A source of air underwater collectable by the pig (ADF)
- [ ] Bumper: Object which bounces you if you touch it (FCF)
- [ ] Cannon: Launches you in a preferred direction when entered, will kill enemies in path
